/**
 * BKB Explorer - Retail Domain Data
 *
 * Auto-generated by run.sh
 * Domain: RBCZ:Retail
 * Concepts: 9
 * External: 5
 *
 * Generated: 2026-01-06T17:46:13.101489
 */

// Lazy-loaded domain data
window.BKB_LOADED = {
  "domain": {
    "path": "RBCZ:Retail",
    "name": "Retail",
    "version": "1.0.0",
    "created": "2026-01-06T17:41:58.940989",
    "sources": []
  },
  "concepts": [
    {
      "id": "dffa3ec4-c74f-40b9-a159-cb6ddab9b221",
      "name": "Account",
      "qname": "bkb-rbcz-retail:Account",
      "type": "concept",
      "sources": [
        {
          "file": "Desktop",
          "line": 0,
          "is_context": false
        }
      ],
      "aliases": [],
      "merged_from": [],
      "local_definition": "",
      "fibo_mapping": {
        "uri": "https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/ClientsAndAccounts/Account",
        "label": "Account",
        "match_type": "exact",
        "confidence": 1.0,
        "fibo_definition": "container for records associated with a business arrangement for regular transactions and services",
        "fibo_module": "",
        "isA": "",
        "skos_relation": "",
        "source": ""
      },
      "definition": {
        "text": "container for records associated with a business arrangement for regular transactions and services",
        "source": "FIBO",
        "confidence": "MAPPED",
        "needs_review": false,
        "parent_name": ""
      },
      "hierarchy": {
        "extends": "https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/ClientsAndAccounts/Account",
        "extends_name": "FIBO:Account",
        "depth": 1,
        "path": [
          "https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/ClientsAndAccounts/Account"
        ]
      },
      "has_fibo_mapping": true,
      "has_schema_mapping": false,
      "has_definition": true,
      "has_parent": true
    },
    {
      "id": "5629d4e5-bf93-430f-a0e2-fb572f26437a",
      "name": "Financial Product",
      "qname": "bkb-rbcz-retail:Financial Product",
      "type": "concept",
      "sources": [
        {
          "file": "Desktop",
          "line": 0,
          "is_context": false
        }
      ],
      "aliases": [],
      "merged_from": [],
      "local_definition": "",
      "fibo_mapping": {
        "uri": "https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/FinancialProduct",
        "label": "Financial Product",
        "match_type": "exact",
        "confidence": 1.0,
        "fibo_definition": "product provided to consumers and businesses by financial institutions such as banks, insurance companies, brokerage firms, consumer finance companies, and investment companies",
        "fibo_module": "",
        "isA": "",
        "skos_relation": "",
        "source": ""
      },
      "definition": {
        "text": "product provided to consumers and businesses by financial institutions such as banks, insurance companies, brokerage firms, consumer finance companies, and investment companies",
        "source": "FIBO",
        "confidence": "MAPPED",
        "needs_review": false,
        "parent_name": ""
      },
      "hierarchy": {
        "extends": "https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/FinancialProduct",
        "extends_name": "FIBO:Financial Product",
        "depth": 1,
        "path": [
          "https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/FinancialProduct"
        ]
      },
      "has_fibo_mapping": true,
      "has_schema_mapping": false,
      "has_definition": true,
      "has_parent": true
    },
    {
      "id": "e613e086-8271-4030-b543-4cc4be8db5e1",
      "name": "Service Product",
      "qname": "bkb-rbcz-retail:Service Product",
      "type": "concept",
      "sources": [
        {
          "file": "Desktop",
          "line": 0,
          "is_context": false
        }
      ],
      "aliases": [],
      "merged_from": [],
      "local_definition": "",
      "fibo_mapping": {
        "uri": "https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/FinancialProduct",
        "label": "Financial Product",
        "match_type": "override",
        "confidence": 1.0,
        "fibo_definition": "product provided to consumers and businesses by financial institutions such as banks, insurance companies, brokerage firms, consumer finance companies, and investment companies",
        "fibo_module": "FIBO-FBC",
        "isA": "fibo:FinancialProduct",
        "skos_relation": "",
        "source": ""
      },
      "definition": {
        "text": "product provided to consumers and businesses by financial institutions such as banks, insurance companies, brokerage firms, consumer finance companies, and investment companies",
        "source": "FIBO",
        "confidence": "MAPPED",
        "needs_review": false,
        "parent_name": ""
      },
      "hierarchy": {
        "extends": "https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/FinancialProduct",
        "extends_name": "FIBO:Financial Product",
        "depth": 1,
        "path": [
          "https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/FinancialProduct"
        ]
      },
      "has_fibo_mapping": true,
      "has_schema_mapping": false,
      "has_definition": true,
      "has_parent": true
    },
    {
      "id": "0e9d9a4e-1069-493b-bb84-55517147c09b",
      "name": "Application",
      "qname": "bkb-rbcz-retail:Application",
      "type": "concept",
      "sources": [
        {
          "file": "Desktop",
          "line": 0,
          "is_context": false
        }
      ],
      "aliases": [],
      "merged_from": [],
      "local_definition": "",
      "fibo_mapping": null,
      "definition": {
        "text": "Application in Retail domain",
        "source": "DRAFT",
        "confidence": "DRAFT",
        "needs_review": true,
        "parent_name": ""
      },
      "hierarchy": {
        "extends": "owl:Thing",
        "extends_name": "Thing",
        "depth": 1,
        "path": [
          "owl:Thing"
        ]
      },
      "has_fibo_mapping": false,
      "has_schema_mapping": false,
      "has_definition": true,
      "has_parent": true
    },
    {
      "id": "e3f178a7-544a-4aa2-b270-32a84d9c2af1",
      "name": "Bank Assurance",
      "qname": "bkb-rbcz-retail:Bank Assurance",
      "type": "concept",
      "sources": [
        {
          "file": "Desktop",
          "line": 0,
          "is_context": false
        }
      ],
      "aliases": [],
      "merged_from": [],
      "local_definition": "",
      "fibo_mapping": {
        "uri": "https://spec.edmcouncil.org/fibo/ontology/FBC/FunctionalEntities/FinancialServicesEntities/InsuranceService",
        "label": "Insurance Service",
        "match_type": "override",
        "confidence": 1.0,
        "fibo_definition": "financial service in which the insurer promises to provide compensation for specific potential future losses in exchange for a periodic payment",
        "fibo_module": "FIBO-FBC",
        "isA": "fibo:InsuranceService",
        "skos_relation": "",
        "source": ""
      },
      "definition": {
        "text": "financial service in which the insurer promises to provide compensation for specific potential future losses in exchange for a periodic payment",
        "source": "FIBO",
        "confidence": "MAPPED",
        "needs_review": false,
        "parent_name": ""
      },
      "hierarchy": {
        "extends": "https://spec.edmcouncil.org/fibo/ontology/FBC/FunctionalEntities/FinancialServicesEntities/InsuranceService",
        "extends_name": "FIBO:Insurance Service",
        "depth": 1,
        "path": [
          "https://spec.edmcouncil.org/fibo/ontology/FBC/FunctionalEntities/FinancialServicesEntities/InsuranceService"
        ]
      },
      "has_fibo_mapping": true,
      "has_schema_mapping": false,
      "has_definition": true,
      "has_parent": true
    },
    {
      "id": "ebb197c1-9b3f-4acb-b428-e13fb6fdd825",
      "name": "Card",
      "qname": "bkb-rbcz-retail:Card",
      "type": "concept",
      "sources": [
        {
          "file": "Desktop",
          "line": 0,
          "is_context": false
        }
      ],
      "aliases": [],
      "merged_from": [],
      "local_definition": "",
      "fibo_mapping": null,
      "definition": {
        "text": "Card in Retail domain",
        "source": "DRAFT",
        "confidence": "DRAFT",
        "needs_review": true,
        "parent_name": ""
      },
      "hierarchy": {
        "extends": "owl:Thing",
        "extends_name": "Thing",
        "depth": 1,
        "path": [
          "owl:Thing"
        ]
      },
      "has_fibo_mapping": false,
      "has_schema_mapping": false,
      "has_definition": true,
      "has_parent": true
    },
    {
      "id": "29529aa9-f7ce-40e2-8a11-c3b32f8017d9",
      "name": "Customer",
      "qname": "bkb-rbcz-retail:Customer",
      "type": "concept",
      "sources": [
        {
          "file": "Desktop",
          "line": 0,
          "is_context": false
        }
      ],
      "aliases": [],
      "merged_from": [],
      "local_definition": "",
      "fibo_mapping": {
        "uri": "https://spec.edmcouncil.org/fibo/ontology/FND/ProductsAndServices/ProductsAndServices/Customer",
        "label": "Customer",
        "match_type": "exact",
        "confidence": 1.0,
        "fibo_definition": "party that receives or consumes products (goods or services) and has the ability to choose between different products and suppliers",
        "fibo_module": "",
        "isA": "",
        "skos_relation": "",
        "source": ""
      },
      "definition": {
        "text": "party that receives or consumes products (goods or services) and has the ability to choose between different products and suppliers",
        "source": "FIBO",
        "confidence": "MAPPED",
        "needs_review": false,
        "parent_name": ""
      },
      "hierarchy": {
        "extends": "https://spec.edmcouncil.org/fibo/ontology/FND/ProductsAndServices/ProductsAndServices/Customer",
        "extends_name": "FIBO:Customer",
        "depth": 1,
        "path": [
          "https://spec.edmcouncil.org/fibo/ontology/FND/ProductsAndServices/ProductsAndServices/Customer"
        ]
      },
      "has_fibo_mapping": true,
      "has_schema_mapping": false,
      "has_definition": true,
      "has_parent": true
    },
    {
      "id": "19a518ff-c974-4c92-ae4d-4f9745256b9e",
      "name": "Investment",
      "qname": "bkb-rbcz-retail:Investment",
      "type": "concept",
      "sources": [
        {
          "file": "Desktop",
          "line": 0,
          "is_context": false
        }
      ],
      "aliases": [],
      "merged_from": [],
      "local_definition": "",
      "fibo_mapping": null,
      "definition": {
        "text": "Investment in Retail domain",
        "source": "DRAFT",
        "confidence": "DRAFT",
        "needs_review": true,
        "parent_name": ""
      },
      "hierarchy": {
        "extends": "owl:Thing",
        "extends_name": "Thing",
        "depth": 1,
        "path": [
          "owl:Thing"
        ]
      },
      "has_fibo_mapping": false,
      "has_schema_mapping": false,
      "has_definition": true,
      "has_parent": true
    },
    {
      "id": "3f447c1f-2dfb-430b-87cb-76b23bcf1d03",
      "name": "Transaction",
      "qname": "bkb-rbcz-retail:Transaction",
      "type": "concept",
      "sources": [
        {
          "file": "Desktop",
          "line": 0,
          "is_context": false
        }
      ],
      "aliases": [],
      "merged_from": [],
      "local_definition": "",
      "fibo_mapping": {
        "uri": "https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/Transaction",
        "label": "Transaction",
        "match_type": "exact",
        "confidence": 1.0,
        "fibo_definition": "An instance of buying or selling something; a business deal or exchange.",
        "fibo_module": "",
        "isA": "",
        "skos_relation": "",
        "source": ""
      },
      "definition": {
        "text": "An instance of buying or selling something; a business deal or exchange.",
        "source": "FIBO",
        "confidence": "MAPPED",
        "needs_review": false,
        "parent_name": ""
      },
      "hierarchy": {
        "extends": "https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/Transaction",
        "extends_name": "FIBO:Transaction",
        "depth": 1,
        "path": [
          "https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/Transaction"
        ]
      },
      "has_fibo_mapping": true,
      "has_schema_mapping": false,
      "has_definition": true,
      "has_parent": true
    }
  ],
  "external_concepts": [
    {
      "name": "Account",
      "label": "Account",
      "uri": "https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/ClientsAndAccounts/Account",
      "qname": "fibo-fbc-pro-cli:Account",
      "type": "fibo",
      "definition": "",
      "sources": [
        {
          "file": "Desktop",
          "inherited_from": "Account",
          "relationship": "extends"
        }
      ]
    },
    {
      "name": "Financial Product",
      "label": "Financial Product",
      "uri": "https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/FinancialProduct",
      "qname": "fibo-fbc-pro-fin:Financial Product",
      "type": "fibo",
      "definition": "",
      "sources": [
        {
          "file": "Desktop",
          "inherited_from": "Financial Product",
          "relationship": "extends"
        }
      ]
    },
    {
      "name": "Insurance Service",
      "label": "Insurance Service",
      "uri": "https://spec.edmcouncil.org/fibo/ontology/FBC/FunctionalEntities/FinancialServicesEntities/InsuranceService",
      "qname": "fibo-fbc-fun-fin:Insurance Service",
      "type": "fibo",
      "definition": "",
      "sources": [
        {
          "file": "Desktop",
          "inherited_from": "Bank Assurance",
          "relationship": "extends"
        }
      ]
    },
    {
      "name": "Customer",
      "label": "Customer",
      "uri": "https://spec.edmcouncil.org/fibo/ontology/FND/ProductsAndServices/ProductsAndServices/Customer",
      "qname": "fibo-fnd-pro-pro:Customer",
      "type": "fibo",
      "definition": "",
      "sources": [
        {
          "file": "Desktop",
          "inherited_from": "Customer",
          "relationship": "extends"
        }
      ]
    },
    {
      "name": "Transaction",
      "label": "Transaction",
      "uri": "https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/Transaction",
      "qname": "fibo-fbc-pro-fin:Transaction",
      "type": "fibo",
      "definition": "",
      "sources": [
        {
          "file": "Desktop",
          "inherited_from": "Transaction",
          "relationship": "extends"
        }
      ]
    }
  ],
  "categorizations": [
    {
      "category_name": "",
      "is_context": false,
      "parent_name": "Service Product",
      "children_names": [
        "Financial Product"
      ]
    }
  ],
  "relationships": [
    {
      "id": "42895961-d29c-4cee-9d2e-beec90f37b75",
      "subject_id": "dffa3ec4-c74f-40b9-a159-cb6ddab9b221",
      "subject_name": "Account",
      "object_id": "5629d4e5-bf93-430f-a0e2-fb572f26437a",
      "object_name": "Financial Product",
      "verb_phrase": "services",
      "inverse_verb_phrase": "is serviced by",
      "role_subject": "",
      "role_object": "",
      "objectification_name": "",
      "is_context": false,
      "sources": [
        {
          "file": "Desktop",
          "line": 0
        }
      ]
    },
    {
      "id": "75e9435e-51f6-4024-9e42-013187000c9e",
      "subject_id": "29529aa9-f7ce-40e2-8a11-c3b32f8017d9",
      "subject_name": "Customer",
      "object_id": "dffa3ec4-c74f-40b9-a159-cb6ddab9b221",
      "object_name": "Account",
      "verb_phrase": "owns",
      "inverse_verb_phrase": "is owned by",
      "role_subject": "",
      "role_object": "",
      "objectification_name": "",
      "is_context": false,
      "sources": [
        {
          "file": "Desktop",
          "line": 0
        }
      ]
    },
    {
      "id": "6bd273cb-e0b4-4161-9c1b-6371fe1900e4",
      "subject_id": "dffa3ec4-c74f-40b9-a159-cb6ddab9b221",
      "subject_name": "Account",
      "object_id": "3f447c1f-2dfb-430b-87cb-76b23bcf1d03",
      "object_name": "Transaction",
      "verb_phrase": "records",
      "inverse_verb_phrase": "is recorded in",
      "role_subject": "",
      "role_object": "",
      "objectification_name": "",
      "is_context": false,
      "sources": [
        {
          "file": "Desktop",
          "line": 0
        }
      ]
    },
    {
      "id": "bc5ab319-ba82-4221-96c3-038ddb2cffdb",
      "subject_id": "29529aa9-f7ce-40e2-8a11-c3b32f8017d9",
      "subject_name": "Customer",
      "object_id": "5629d4e5-bf93-430f-a0e2-fb572f26437a",
      "object_name": "Financial Product",
      "verb_phrase": "purchases",
      "inverse_verb_phrase": "is purchased by",
      "role_subject": "",
      "role_object": "",
      "objectification_name": "",
      "is_context": false,
      "sources": [
        {
          "file": "Desktop",
          "line": 0
        }
      ]
    },
    {
      "id": "57bbf0f9-1ca8-4bc8-a06f-2377f22a5fa0",
      "subject_id": "3f447c1f-2dfb-430b-87cb-76b23bcf1d03",
      "subject_name": "Transaction",
      "object_id": "5629d4e5-bf93-430f-a0e2-fb572f26437a",
      "object_name": "Financial Product",
      "verb_phrase": "realizes",
      "inverse_verb_phrase": "is realized by",
      "role_subject": "",
      "role_object": "",
      "objectification_name": "",
      "is_context": false,
      "sources": [
        {
          "file": "Desktop",
          "line": 0
        }
      ]
    },
    {
      "id": "e1aaf748-acd1-49ad-a6db-90cda8665a15",
      "subject_id": "29529aa9-f7ce-40e2-8a11-c3b32f8017d9",
      "subject_name": "Customer",
      "object_id": "ebb197c1-9b3f-4acb-b428-e13fb6fdd825",
      "object_name": "Card",
      "verb_phrase": "uses",
      "inverse_verb_phrase": "is used by",
      "role_subject": "",
      "role_object": "",
      "objectification_name": "",
      "is_context": false,
      "sources": [
        {
          "file": "Desktop",
          "line": 0
        }
      ]
    },
    {
      "id": "bf059ddd-7d95-4170-9f05-052e2e837795",
      "subject_id": "ebb197c1-9b3f-4acb-b428-e13fb6fdd825",
      "subject_name": "Card",
      "object_id": "dffa3ec4-c74f-40b9-a159-cb6ddab9b221",
      "object_name": "Account",
      "verb_phrase": "draws from",
      "inverse_verb_phrase": "is source for",
      "role_subject": "",
      "role_object": "",
      "objectification_name": "",
      "is_context": false,
      "sources": [
        {
          "file": "Desktop",
          "line": 0
        }
      ]
    },
    {
      "id": "18be0ffb-916b-42be-943d-3aecfe709566",
      "subject_id": "ebb197c1-9b3f-4acb-b428-e13fb6fdd825",
      "subject_name": "Card",
      "object_id": "3f447c1f-2dfb-430b-87cb-76b23bcf1d03",
      "object_name": "Transaction",
      "verb_phrase": "is used for",
      "inverse_verb_phrase": "uses",
      "role_subject": "",
      "role_object": "",
      "objectification_name": "",
      "is_context": false,
      "sources": [
        {
          "file": "Desktop",
          "line": 0
        }
      ]
    },
    {
      "id": "897b2dd1-50da-472e-a6cb-c2cf1b7bec04",
      "subject_id": "29529aa9-f7ce-40e2-8a11-c3b32f8017d9",
      "subject_name": "Customer",
      "object_id": "19a518ff-c974-4c92-ae4d-4f9745256b9e",
      "object_name": "Investment",
      "verb_phrase": "owns",
      "inverse_verb_phrase": "is owned by",
      "role_subject": "",
      "role_object": "",
      "objectification_name": "",
      "is_context": false,
      "sources": [
        {
          "file": "Desktop",
          "line": 0
        }
      ]
    },
    {
      "id": "1b612d5b-ad28-4b34-a068-e3ee6829ffa1",
      "subject_id": "29529aa9-f7ce-40e2-8a11-c3b32f8017d9",
      "subject_name": "Customer",
      "object_id": "e3f178a7-544a-4aa2-b270-32a84d9c2af1",
      "object_name": "Bank Assurance",
      "verb_phrase": "holds",
      "inverse_verb_phrase": "is held by",
      "role_subject": "",
      "role_object": "",
      "objectification_name": "",
      "is_context": false,
      "sources": [
        {
          "file": "Desktop",
          "line": 0
        }
      ]
    },
    {
      "id": "74484219-aad2-4064-9b50-4da7e2a8bbe5",
      "subject_id": "19a518ff-c974-4c92-ae4d-4f9745256b9e",
      "subject_name": "Investment",
      "object_id": "dffa3ec4-c74f-40b9-a159-cb6ddab9b221",
      "object_name": "Account",
      "verb_phrase": "is held in",
      "inverse_verb_phrase": "holds",
      "role_subject": "",
      "role_object": "",
      "objectification_name": "",
      "is_context": false,
      "sources": [
        {
          "file": "Desktop",
          "line": 0
        }
      ]
    },
    {
      "id": "4b708bd2-d93e-4728-8024-fd9706ca66aa",
      "subject_id": "5629d4e5-bf93-430f-a0e2-fb572f26437a",
      "subject_name": "Financial Product",
      "object_id": "19a518ff-c974-4c92-ae4d-4f9745256b9e",
      "object_name": "Investment",
      "verb_phrase": "is related by",
      "inverse_verb_phrase": "relates to",
      "role_subject": "",
      "role_object": "",
      "objectification_name": "",
      "is_context": false,
      "sources": [
        {
          "file": "Desktop",
          "line": 0
        }
      ]
    },
    {
      "id": "66b05290-216c-4381-a689-f04d7d42dedb",
      "subject_id": "3f447c1f-2dfb-430b-87cb-76b23bcf1d03",
      "subject_name": "Transaction",
      "object_id": "19a518ff-c974-4c92-ae4d-4f9745256b9e",
      "object_name": "Investment",
      "verb_phrase": "affects",
      "inverse_verb_phrase": "is affected by",
      "role_subject": "",
      "role_object": "",
      "objectification_name": "",
      "is_context": false,
      "sources": [
        {
          "file": "Desktop",
          "line": 0
        }
      ]
    },
    {
      "id": "45dd205c-d5e1-4127-9bd9-0d9f8d3ac438",
      "subject_id": "29529aa9-f7ce-40e2-8a11-c3b32f8017d9",
      "subject_name": "Customer",
      "object_id": "0e9d9a4e-1069-493b-bb84-55517147c09b",
      "object_name": "Application",
      "verb_phrase": "submits",
      "inverse_verb_phrase": "is submitted by",
      "role_subject": "",
      "role_object": "",
      "objectification_name": "",
      "is_context": false,
      "sources": [
        {
          "file": "Desktop",
          "line": 0
        }
      ]
    },
    {
      "id": "02030416-7869-4204-8f8f-066e7cac333a",
      "subject_id": "0e9d9a4e-1069-493b-bb84-55517147c09b",
      "subject_name": "Application",
      "object_id": "5629d4e5-bf93-430f-a0e2-fb572f26437a",
      "object_name": "Financial Product",
      "verb_phrase": "requests",
      "inverse_verb_phrase": "is requested by",
      "role_subject": "",
      "role_object": "",
      "objectification_name": "",
      "is_context": false,
      "sources": [
        {
          "file": "Desktop",
          "line": 0
        }
      ]
    }
  ],
  "enumerations": [],
  "unary_states": [],
  "subsumptions": [],
  "properties": [],
  "property_types": [],
  "mapping": null,
  "metadata": {
    "concept_count": 9,
    "external_concept_count": 0,
    "fibo_mapped_count": 6,
    "fibo_coverage": 66.66666666666666,
    "schema_mapped_count": 0,
    "semantic_coverage": 66.66666666666666,
    "definition_coverage": 100.0,
    "exact_matches": 4,
    "synonym_matches": 0,
    "fuzzy_matches": 0,
    "keyword_matches": 0,
    "parent_matches": 0,
    "hierarchical_matches": 0,
    "llm_matches": 0,
    "override_matches": 2,
    "yaml_links_matches": 0,
    "meta_suffix_matches": 0,
    "meta_prefix_matches": 0,
    "status_prefix_matches": 0,
    "type_suffix_matches": 0,
    "no_matches": 3,
    "non_fibo_count": 3,
    "draft_definitions": 3,
    "validation_errors": [],
    "validation_warnings": [
      "3 concepts have DRAFT definitions that need review"
    ]
  },
  "schema_version": "1.0.0",
  "created_at": "2026-01-06T17:44:27.351140",
  "modified_at": "2026-01-06T17:44:27.351152",
  "generated": "2026-01-06T17:44:27.351153",
  "fibo_version": "2024Q1"
};

console.log('✅ Loaded Retail:', 9 + 5, 'concepts');
