/**
 * BKB Explorer - Retail Domain Data
 *
 * Auto-generated by run.sh
 * Domain: RBCZ:Retail
 * Concepts: 9
 * External: 5
 *
 * Generated: 2026-01-04T11:48:46.950256
 */

// Lazy-loaded domain data
window.BKB_LOADED = {
  "domain": {
    "path": "RBCZ:MIB:Retail",
    "name": "Retail",
    "version": "1.0.0",
    "created": "2026-01-04T07:05:36.291922",
    "sources": []
  },
  "concepts": [
    {
      "id": "6f9023bc-8b8a-4a7a-b11a-473e88f28f5a",
      "name": "Account",
      "qname": "bkb-rbcz-mib-retail:Account",
      "type": "concept",
      "sources": [
        {
          "file": "Desktop",
          "line": 0,
          "is_context": false
        }
      ],
      "aliases": [],
      "merged_from": [],
      "local_definition": "",
      "fibo_mapping": {
        "uri": "https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/ClientsAndAccounts/Account",
        "label": "Account",
        "match_type": "exact",
        "confidence": 1.0,
        "fibo_definition": "container for records associated with a business arrangement for regular transactions and services",
        "fibo_module": "",
        "isA": "",
        "skos_relation": "",
        "source": ""
      },
      "definition": {
        "text": "container for records associated with a business arrangement for regular transactions and services",
        "source": "FIBO",
        "confidence": "MAPPED",
        "needs_review": false,
        "parent_name": ""
      },
      "hierarchy": {
        "extends": "https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/ClientsAndAccounts/Account",
        "extends_name": "FIBO:Account",
        "depth": 1,
        "path": [
          "https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/ClientsAndAccounts/Account"
        ]
      },
      "has_fibo_mapping": true,
      "has_schema_mapping": false,
      "has_definition": true,
      "has_parent": true
    },
    {
      "id": "2217e41d-cdf6-4465-a05e-826c3fdc1681",
      "name": "Financial Product",
      "qname": "bkb-rbcz-mib-retail:Financial Product",
      "type": "concept",
      "sources": [
        {
          "file": "Desktop",
          "line": 0,
          "is_context": false
        }
      ],
      "aliases": [],
      "merged_from": [],
      "local_definition": "",
      "fibo_mapping": {
        "uri": "https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/FinancialProduct",
        "label": "Financial Product",
        "match_type": "exact",
        "confidence": 1.0,
        "fibo_definition": "product provided to consumers and businesses by financial institutions such as banks, insurance companies, brokerage firms, consumer finance companies, and investment companies",
        "fibo_module": "",
        "isA": "",
        "skos_relation": "",
        "source": ""
      },
      "definition": {
        "text": "product provided to consumers and businesses by financial institutions such as banks, insurance companies, brokerage firms, consumer finance companies, and investment companies",
        "source": "FIBO",
        "confidence": "MAPPED",
        "needs_review": false,
        "parent_name": ""
      },
      "hierarchy": {
        "extends": "https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/FinancialProduct",
        "extends_name": "FIBO:Financial Product",
        "depth": 1,
        "path": [
          "https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/FinancialProduct"
        ]
      },
      "has_fibo_mapping": true,
      "has_schema_mapping": false,
      "has_definition": true,
      "has_parent": true
    },
    {
      "id": "0a0f1d9d-bc87-492b-8bf6-f638f222cdd2",
      "name": "Service Product",
      "qname": "bkb-rbcz-mib-retail:Service Product",
      "type": "concept",
      "sources": [
        {
          "file": "Desktop",
          "line": 0,
          "is_context": false
        }
      ],
      "aliases": [],
      "merged_from": [],
      "local_definition": "",
      "fibo_mapping": {
        "uri": "https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/FinancialProduct",
        "label": "Financial Product",
        "match_type": "override",
        "confidence": 1.0,
        "fibo_definition": "product provided to consumers and businesses by financial institutions such as banks, insurance companies, brokerage firms, consumer finance companies, and investment companies",
        "fibo_module": "FIBO-FBC",
        "isA": "fibo:FinancialProduct",
        "skos_relation": "",
        "source": ""
      },
      "definition": {
        "text": "product provided to consumers and businesses by financial institutions such as banks, insurance companies, brokerage firms, consumer finance companies, and investment companies",
        "source": "FIBO",
        "confidence": "MAPPED",
        "needs_review": false,
        "parent_name": ""
      },
      "hierarchy": {
        "extends": "https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/FinancialProduct",
        "extends_name": "FIBO:Financial Product",
        "depth": 1,
        "path": [
          "https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/FinancialProduct"
        ]
      },
      "has_fibo_mapping": true,
      "has_schema_mapping": false,
      "has_definition": true,
      "has_parent": true
    },
    {
      "id": "1bde40a9-54fe-4d20-a84e-3a8a77e2ff2f",
      "name": "Application",
      "qname": "bkb-rbcz-mib-retail:Application",
      "type": "concept",
      "sources": [
        {
          "file": "Desktop",
          "line": 0,
          "is_context": false
        }
      ],
      "aliases": [],
      "merged_from": [],
      "local_definition": "",
      "fibo_mapping": null,
      "definition": {
        "text": "Application in Retail domain",
        "source": "DRAFT",
        "confidence": "DRAFT",
        "needs_review": true,
        "parent_name": ""
      },
      "hierarchy": {
        "extends": "owl:Thing",
        "extends_name": "Thing",
        "depth": 1,
        "path": [
          "owl:Thing"
        ]
      },
      "has_fibo_mapping": false,
      "has_schema_mapping": false,
      "has_definition": true,
      "has_parent": true
    },
    {
      "id": "213182a7-24a9-4bdd-aa4b-f16c1c1ae833",
      "name": "Bank Assurance",
      "qname": "bkb-rbcz-mib-retail:Bank Assurance",
      "type": "concept",
      "sources": [
        {
          "file": "Desktop",
          "line": 0,
          "is_context": false
        }
      ],
      "aliases": [],
      "merged_from": [],
      "local_definition": "",
      "fibo_mapping": {
        "uri": "https://spec.edmcouncil.org/fibo/ontology/FBC/FunctionalEntities/FinancialServicesEntities/InsuranceService",
        "label": "Insurance Service",
        "match_type": "override",
        "confidence": 1.0,
        "fibo_definition": "financial service in which the insurer promises to provide compensation for specific potential future losses in exchange for a periodic payment",
        "fibo_module": "FIBO-FBC",
        "isA": "fibo:InsuranceService",
        "skos_relation": "",
        "source": ""
      },
      "definition": {
        "text": "financial service in which the insurer promises to provide compensation for specific potential future losses in exchange for a periodic payment",
        "source": "FIBO",
        "confidence": "MAPPED",
        "needs_review": false,
        "parent_name": ""
      },
      "hierarchy": {
        "extends": "https://spec.edmcouncil.org/fibo/ontology/FBC/FunctionalEntities/FinancialServicesEntities/InsuranceService",
        "extends_name": "FIBO:Insurance Service",
        "depth": 1,
        "path": [
          "https://spec.edmcouncil.org/fibo/ontology/FBC/FunctionalEntities/FinancialServicesEntities/InsuranceService"
        ]
      },
      "has_fibo_mapping": true,
      "has_schema_mapping": false,
      "has_definition": true,
      "has_parent": true
    },
    {
      "id": "a0f72c8a-95bc-496d-91a3-c774d6ba24b1",
      "name": "Card",
      "qname": "bkb-rbcz-mib-retail:Card",
      "type": "concept",
      "sources": [
        {
          "file": "Desktop",
          "line": 0,
          "is_context": false
        }
      ],
      "aliases": [],
      "merged_from": [],
      "local_definition": "",
      "fibo_mapping": null,
      "definition": {
        "text": "Card in Retail domain",
        "source": "DRAFT",
        "confidence": "DRAFT",
        "needs_review": true,
        "parent_name": ""
      },
      "hierarchy": {
        "extends": "owl:Thing",
        "extends_name": "Thing",
        "depth": 1,
        "path": [
          "owl:Thing"
        ]
      },
      "has_fibo_mapping": false,
      "has_schema_mapping": false,
      "has_definition": true,
      "has_parent": true
    },
    {
      "id": "1fdf4ac8-863e-4666-b5f4-de48767fd975",
      "name": "Customer",
      "qname": "bkb-rbcz-mib-retail:Customer",
      "type": "concept",
      "sources": [
        {
          "file": "Desktop",
          "line": 0,
          "is_context": false
        }
      ],
      "aliases": [],
      "merged_from": [],
      "local_definition": "",
      "fibo_mapping": {
        "uri": "https://spec.edmcouncil.org/fibo/ontology/FND/ProductsAndServices/ProductsAndServices/Customer",
        "label": "Customer",
        "match_type": "exact",
        "confidence": 1.0,
        "fibo_definition": "party that receives or consumes products (goods or services) and has the ability to choose between different products and suppliers",
        "fibo_module": "",
        "isA": "",
        "skos_relation": "",
        "source": ""
      },
      "definition": {
        "text": "party that receives or consumes products (goods or services) and has the ability to choose between different products and suppliers",
        "source": "FIBO",
        "confidence": "MAPPED",
        "needs_review": false,
        "parent_name": ""
      },
      "hierarchy": {
        "extends": "https://spec.edmcouncil.org/fibo/ontology/FND/ProductsAndServices/ProductsAndServices/Customer",
        "extends_name": "FIBO:Customer",
        "depth": 1,
        "path": [
          "https://spec.edmcouncil.org/fibo/ontology/FND/ProductsAndServices/ProductsAndServices/Customer"
        ]
      },
      "has_fibo_mapping": true,
      "has_schema_mapping": false,
      "has_definition": true,
      "has_parent": true
    },
    {
      "id": "bdc283b0-1340-4b38-a8fc-e4b6c7bd8ebf",
      "name": "Investment",
      "qname": "bkb-rbcz-mib-retail:Investment",
      "type": "concept",
      "sources": [
        {
          "file": "Desktop",
          "line": 0,
          "is_context": false
        }
      ],
      "aliases": [],
      "merged_from": [],
      "local_definition": "",
      "fibo_mapping": null,
      "definition": {
        "text": "Investment in Retail domain",
        "source": "DRAFT",
        "confidence": "DRAFT",
        "needs_review": true,
        "parent_name": ""
      },
      "hierarchy": {
        "extends": "owl:Thing",
        "extends_name": "Thing",
        "depth": 1,
        "path": [
          "owl:Thing"
        ]
      },
      "has_fibo_mapping": false,
      "has_schema_mapping": false,
      "has_definition": true,
      "has_parent": true
    },
    {
      "id": "b27347eb-e05d-40a3-ac77-35349653dd8a",
      "name": "Transaction",
      "qname": "bkb-rbcz-mib-retail:Transaction",
      "type": "concept",
      "sources": [
        {
          "file": "Desktop",
          "line": 0,
          "is_context": false
        }
      ],
      "aliases": [],
      "merged_from": [],
      "local_definition": "",
      "fibo_mapping": {
        "uri": "https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/Transaction",
        "label": "Transaction",
        "match_type": "exact",
        "confidence": 1.0,
        "fibo_definition": "An instance of buying or selling something; a business deal or exchange.",
        "fibo_module": "",
        "isA": "",
        "skos_relation": "",
        "source": ""
      },
      "definition": {
        "text": "An instance of buying or selling something; a business deal or exchange.",
        "source": "FIBO",
        "confidence": "MAPPED",
        "needs_review": false,
        "parent_name": ""
      },
      "hierarchy": {
        "extends": "https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/Transaction",
        "extends_name": "FIBO:Transaction",
        "depth": 1,
        "path": [
          "https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/Transaction"
        ]
      },
      "has_fibo_mapping": true,
      "has_schema_mapping": false,
      "has_definition": true,
      "has_parent": true
    }
  ],
  "external_concepts": [
    {
      "name": "Account",
      "label": "Account",
      "uri": "https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/ClientsAndAccounts/Account",
      "qname": "fibo-fbc-pro-cli:Account",
      "type": "fibo",
      "definition": "",
      "sources": [
        {
          "file": "Desktop",
          "inherited_from": "Account",
          "relationship": "extends"
        }
      ]
    },
    {
      "name": "Financial Product",
      "label": "Financial Product",
      "uri": "https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/FinancialProduct",
      "qname": "fibo-fbc-pro-fin:Financial Product",
      "type": "fibo",
      "definition": "",
      "sources": [
        {
          "file": "Desktop",
          "inherited_from": "Financial Product",
          "relationship": "extends"
        }
      ]
    },
    {
      "name": "Insurance Service",
      "label": "Insurance Service",
      "uri": "https://spec.edmcouncil.org/fibo/ontology/FBC/FunctionalEntities/FinancialServicesEntities/InsuranceService",
      "qname": "fibo-fbc-fun-fin:Insurance Service",
      "type": "fibo",
      "definition": "",
      "sources": [
        {
          "file": "Desktop",
          "inherited_from": "Bank Assurance",
          "relationship": "extends"
        }
      ]
    },
    {
      "name": "Customer",
      "label": "Customer",
      "uri": "https://spec.edmcouncil.org/fibo/ontology/FND/ProductsAndServices/ProductsAndServices/Customer",
      "qname": "fibo-fnd-pro-pro:Customer",
      "type": "fibo",
      "definition": "",
      "sources": [
        {
          "file": "Desktop",
          "inherited_from": "Customer",
          "relationship": "extends"
        }
      ]
    },
    {
      "name": "Transaction",
      "label": "Transaction",
      "uri": "https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/Transaction",
      "qname": "fibo-fbc-pro-fin:Transaction",
      "type": "fibo",
      "definition": "",
      "sources": [
        {
          "file": "Desktop",
          "inherited_from": "Transaction",
          "relationship": "extends"
        }
      ]
    }
  ],
  "categorizations": [
    {
      "category_name": "",
      "is_context": false,
      "parent_name": "Service Product",
      "children_names": [
        "Financial Product"
      ]
    }
  ],
  "relationships": [
    {
      "id": "e9a662a5-9b9a-4dd4-9fd5-3317aefbecef",
      "subject_id": "6f9023bc-8b8a-4a7a-b11a-473e88f28f5a",
      "subject_name": "Account",
      "object_id": "2217e41d-cdf6-4465-a05e-826c3fdc1681",
      "object_name": "Financial Product",
      "verb_phrase": "services",
      "inverse_verb_phrase": "is serviced by",
      "role_subject": "",
      "role_object": "",
      "objectification_name": "",
      "is_context": false,
      "sources": [
        {
          "file": "Desktop",
          "line": 0
        }
      ]
    },
    {
      "id": "db576026-7203-4a77-9797-d21120ae2f84",
      "subject_id": "1fdf4ac8-863e-4666-b5f4-de48767fd975",
      "subject_name": "Customer",
      "object_id": "6f9023bc-8b8a-4a7a-b11a-473e88f28f5a",
      "object_name": "Account",
      "verb_phrase": "owns",
      "inverse_verb_phrase": "is owned by",
      "role_subject": "",
      "role_object": "",
      "objectification_name": "",
      "is_context": false,
      "sources": [
        {
          "file": "Desktop",
          "line": 0
        }
      ]
    },
    {
      "id": "13eb6818-79ae-4a8f-821b-5fdb93f97ee6",
      "subject_id": "6f9023bc-8b8a-4a7a-b11a-473e88f28f5a",
      "subject_name": "Account",
      "object_id": "b27347eb-e05d-40a3-ac77-35349653dd8a",
      "object_name": "Transaction",
      "verb_phrase": "records",
      "inverse_verb_phrase": "is recorded in",
      "role_subject": "",
      "role_object": "",
      "objectification_name": "",
      "is_context": false,
      "sources": [
        {
          "file": "Desktop",
          "line": 0
        }
      ]
    },
    {
      "id": "b42fc458-1b0f-4095-8d35-bed74370b872",
      "subject_id": "1fdf4ac8-863e-4666-b5f4-de48767fd975",
      "subject_name": "Customer",
      "object_id": "2217e41d-cdf6-4465-a05e-826c3fdc1681",
      "object_name": "Financial Product",
      "verb_phrase": "purchases",
      "inverse_verb_phrase": "is purchased by",
      "role_subject": "",
      "role_object": "",
      "objectification_name": "",
      "is_context": false,
      "sources": [
        {
          "file": "Desktop",
          "line": 0
        }
      ]
    },
    {
      "id": "899d9ce7-f7ea-4d53-8134-456e5c616b79",
      "subject_id": "b27347eb-e05d-40a3-ac77-35349653dd8a",
      "subject_name": "Transaction",
      "object_id": "2217e41d-cdf6-4465-a05e-826c3fdc1681",
      "object_name": "Financial Product",
      "verb_phrase": "realizes",
      "inverse_verb_phrase": "is realized by",
      "role_subject": "",
      "role_object": "",
      "objectification_name": "",
      "is_context": false,
      "sources": [
        {
          "file": "Desktop",
          "line": 0
        }
      ]
    },
    {
      "id": "a821aaca-8d62-4c31-af5e-51cefcb7e1f3",
      "subject_id": "1fdf4ac8-863e-4666-b5f4-de48767fd975",
      "subject_name": "Customer",
      "object_id": "a0f72c8a-95bc-496d-91a3-c774d6ba24b1",
      "object_name": "Card",
      "verb_phrase": "uses",
      "inverse_verb_phrase": "is used by",
      "role_subject": "",
      "role_object": "",
      "objectification_name": "",
      "is_context": false,
      "sources": [
        {
          "file": "Desktop",
          "line": 0
        }
      ]
    },
    {
      "id": "a8e14dae-5d93-4d11-91a9-0d8049d2d3f4",
      "subject_id": "a0f72c8a-95bc-496d-91a3-c774d6ba24b1",
      "subject_name": "Card",
      "object_id": "6f9023bc-8b8a-4a7a-b11a-473e88f28f5a",
      "object_name": "Account",
      "verb_phrase": "draws from",
      "inverse_verb_phrase": "is source for",
      "role_subject": "",
      "role_object": "",
      "objectification_name": "",
      "is_context": false,
      "sources": [
        {
          "file": "Desktop",
          "line": 0
        }
      ]
    },
    {
      "id": "dddc4cac-1904-4a7f-99d5-0a8c7f561794",
      "subject_id": "a0f72c8a-95bc-496d-91a3-c774d6ba24b1",
      "subject_name": "Card",
      "object_id": "b27347eb-e05d-40a3-ac77-35349653dd8a",
      "object_name": "Transaction",
      "verb_phrase": "is used for",
      "inverse_verb_phrase": "uses",
      "role_subject": "",
      "role_object": "",
      "objectification_name": "",
      "is_context": false,
      "sources": [
        {
          "file": "Desktop",
          "line": 0
        }
      ]
    },
    {
      "id": "ad5f46de-e7f5-4fa0-8538-dfafb0fb8f26",
      "subject_id": "1fdf4ac8-863e-4666-b5f4-de48767fd975",
      "subject_name": "Customer",
      "object_id": "bdc283b0-1340-4b38-a8fc-e4b6c7bd8ebf",
      "object_name": "Investment",
      "verb_phrase": "owns",
      "inverse_verb_phrase": "is owned by",
      "role_subject": "",
      "role_object": "",
      "objectification_name": "",
      "is_context": false,
      "sources": [
        {
          "file": "Desktop",
          "line": 0
        }
      ]
    },
    {
      "id": "fc741257-37e0-4530-a088-56a849120bca",
      "subject_id": "1fdf4ac8-863e-4666-b5f4-de48767fd975",
      "subject_name": "Customer",
      "object_id": "213182a7-24a9-4bdd-aa4b-f16c1c1ae833",
      "object_name": "Bank Assurance",
      "verb_phrase": "holds",
      "inverse_verb_phrase": "is held by",
      "role_subject": "",
      "role_object": "",
      "objectification_name": "",
      "is_context": false,
      "sources": [
        {
          "file": "Desktop",
          "line": 0
        }
      ]
    },
    {
      "id": "f18b537e-cc0c-4fef-86fa-00db20015c65",
      "subject_id": "bdc283b0-1340-4b38-a8fc-e4b6c7bd8ebf",
      "subject_name": "Investment",
      "object_id": "6f9023bc-8b8a-4a7a-b11a-473e88f28f5a",
      "object_name": "Account",
      "verb_phrase": "is held in",
      "inverse_verb_phrase": "holds",
      "role_subject": "",
      "role_object": "",
      "objectification_name": "",
      "is_context": false,
      "sources": [
        {
          "file": "Desktop",
          "line": 0
        }
      ]
    },
    {
      "id": "10732f54-2c8e-4d51-aac3-f82f082b9afd",
      "subject_id": "2217e41d-cdf6-4465-a05e-826c3fdc1681",
      "subject_name": "Financial Product",
      "object_id": "bdc283b0-1340-4b38-a8fc-e4b6c7bd8ebf",
      "object_name": "Investment",
      "verb_phrase": "is related by",
      "inverse_verb_phrase": "relates to",
      "role_subject": "",
      "role_object": "",
      "objectification_name": "",
      "is_context": false,
      "sources": [
        {
          "file": "Desktop",
          "line": 0
        }
      ]
    },
    {
      "id": "36d5ef9f-1bb0-47aa-a80f-df1ee779cd48",
      "subject_id": "b27347eb-e05d-40a3-ac77-35349653dd8a",
      "subject_name": "Transaction",
      "object_id": "bdc283b0-1340-4b38-a8fc-e4b6c7bd8ebf",
      "object_name": "Investment",
      "verb_phrase": "affects",
      "inverse_verb_phrase": "is affected by",
      "role_subject": "",
      "role_object": "",
      "objectification_name": "",
      "is_context": false,
      "sources": [
        {
          "file": "Desktop",
          "line": 0
        }
      ]
    },
    {
      "id": "21f1ccfa-d944-45d8-9988-4e938b26b6a4",
      "subject_id": "1fdf4ac8-863e-4666-b5f4-de48767fd975",
      "subject_name": "Customer",
      "object_id": "1bde40a9-54fe-4d20-a84e-3a8a77e2ff2f",
      "object_name": "Application",
      "verb_phrase": "submits",
      "inverse_verb_phrase": "is submitted by",
      "role_subject": "",
      "role_object": "",
      "objectification_name": "",
      "is_context": false,
      "sources": [
        {
          "file": "Desktop",
          "line": 0
        }
      ]
    },
    {
      "id": "d8eb1608-80c9-4cc3-b8b5-d153f1733785",
      "subject_id": "1bde40a9-54fe-4d20-a84e-3a8a77e2ff2f",
      "subject_name": "Application",
      "object_id": "2217e41d-cdf6-4465-a05e-826c3fdc1681",
      "object_name": "Financial Product",
      "verb_phrase": "requests",
      "inverse_verb_phrase": "is requested by",
      "role_subject": "",
      "role_object": "",
      "objectification_name": "",
      "is_context": false,
      "sources": [
        {
          "file": "Desktop",
          "line": 0
        }
      ]
    }
  ],
  "enumerations": [],
  "unary_states": [],
  "subsumptions": [],
  "properties": [],
  "property_types": [],
  "mapping": null,
  "metadata": {
    "concept_count": 9,
    "external_concept_count": 0,
    "fibo_mapped_count": 6,
    "fibo_coverage": 66.66666666666666,
    "schema_mapped_count": 0,
    "semantic_coverage": 66.66666666666666,
    "definition_coverage": 100.0,
    "exact_matches": 4,
    "synonym_matches": 0,
    "fuzzy_matches": 0,
    "keyword_matches": 0,
    "parent_matches": 0,
    "hierarchical_matches": 0,
    "llm_matches": 0,
    "override_matches": 2,
    "yaml_links_matches": 0,
    "meta_suffix_matches": 0,
    "meta_prefix_matches": 0,
    "status_prefix_matches": 0,
    "type_suffix_matches": 0,
    "no_matches": 3,
    "non_fibo_count": 3,
    "draft_definitions": 3,
    "validation_errors": [],
    "validation_warnings": [
      "3 concepts have DRAFT definitions that need review"
    ]
  },
  "schema_version": "1.0.0",
  "created_at": "2026-01-04T11:19:08.464443",
  "modified_at": "2026-01-04T11:19:08.464459",
  "generated": "2026-01-04T11:19:08.464461",
  "fibo_version": "2024Q1"
};

console.log('✅ Loaded Retail:', 9 + 5, 'concepts');
