#!/bin/bash
#
# BKB Explorer - Organization Data Preparation Script
#
# Copies ontology data from ontology-lift/export and bundles it
# into js/data-org.js for local use.
#
# This file is NEVER committed (gitignored). For public repository,
# only test data (in data.js) is available.
#
# Usage: ./prepare-demo.sh
#

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTPUT_FILE="$SCRIPT_DIR/js/data-org.js"
ONTOLOGY_LIFT_DIR="$SCRIPT_DIR/../semantic-platform/ontology_lift"

echo "🔐 BKB Explorer - Preparing organization data (private, never committed)..."
echo ""

# Check if ontology-lift exists
if [ ! -d "$ONTOLOGY_LIFT_DIR" ]; then
    echo "❌ Error: ontology-lift directory not found at $ONTOLOGY_LIFT_DIR"
    exit 1
fi

# Find export directories
EXPORT_DIR="$ONTOLOGY_LIFT_DIR/export"
if [ ! -d "$EXPORT_DIR" ]; then
    # Try demo output
    EXPORT_DIR="$ONTOLOGY_LIFT_DIR/demo/output/cross-domain"
fi

if [ ! -d "$EXPORT_DIR" ]; then
    echo "❌ Error: No export directory found. Run ontology-lift pipeline first."
    exit 1
fi

echo "📂 Using export directory: $EXPORT_DIR"
echo ""

# Find ontology.json files
INVESTMENT_FILE=$(find "$EXPORT_DIR" -path "*Investment*" -name "ontology.json" | head -1)
PAYMENTS_FILE=$(find "$EXPORT_DIR" -path "*Payment*" -name "ontology.json" | head -1)
RETAIL_FILE=$(find "$EXPORT_DIR" -path "*Retail*" -name "ontology.json" | head -1)

# Generate data-org.js
echo "📝 Generating $OUTPUT_FILE..."
echo ""

cat > "$OUTPUT_FILE" << 'HEADER'
/**
 * BKB Explorer - Organization Data (PRIVATE)
 *
 * Auto-generated by prepare-demo.sh
 * DO NOT COMMIT - this file is gitignored
 *
HEADER

echo " * Generated: $(date)" >> "$OUTPUT_FILE"
echo " */" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Count concepts
INV_COUNT=0
PAY_COUNT=0
RET_COUNT=0

if [ -f "$INVESTMENT_FILE" ]; then
    INV_COUNT=$(python3 -c "import json; print(len(json.load(open('$INVESTMENT_FILE'))['concepts']))" 2>/dev/null || echo 0)
fi
if [ -f "$PAYMENTS_FILE" ]; then
    PAY_COUNT=$(python3 -c "import json; print(len(json.load(open('$PAYMENTS_FILE'))['concepts']))" 2>/dev/null || echo 0)
fi
if [ -f "$RETAIL_FILE" ]; then
    RET_COUNT=$(python3 -c "import json; print(len(json.load(open('$RETAIL_FILE'))['concepts']))" 2>/dev/null || echo 0)
fi

# Organization Domains hierarchy
echo "// Organization Domain hierarchy (private)" >> "$OUTPUT_FILE"
echo "const ORG_DOMAINS_DATA = {" >> "$OUTPUT_FILE"
echo '  "hierarchy": {' >> "$OUTPUT_FILE"
echo '    "RBCZ": {' >> "$OUTPUT_FILE"
echo '      "type": "enterprise",' >> "$OUTPUT_FILE"
echo '      "children": {' >> "$OUTPUT_FILE"
echo '        "MIB": {' >> "$OUTPUT_FILE"
echo '          "type": "business_unit",' >> "$OUTPUT_FILE"
echo '          "children": {' >> "$OUTPUT_FILE"
echo "            \"Investment\": { \"type\": \"domain\", \"stats\": { \"concepts\": $INV_COUNT } }," >> "$OUTPUT_FILE"
echo "            \"Payments\": { \"type\": \"domain\", \"stats\": { \"concepts\": $PAY_COUNT } }" >> "$OUTPUT_FILE"
echo '          }' >> "$OUTPUT_FILE"
echo '        },' >> "$OUTPUT_FILE"
echo "        \"Retail\": { \"type\": \"domain\", \"stats\": { \"concepts\": $RET_COUNT } }" >> "$OUTPUT_FILE"
echo '      }' >> "$OUTPUT_FILE"
echo '    }' >> "$OUTPUT_FILE"
echo '  }' >> "$OUTPUT_FILE"
echo '};' >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Investment data
echo "// Investment domain" >> "$OUTPUT_FILE"
echo -n "const INVESTMENT_DATA = " >> "$OUTPUT_FILE"
if [ -f "$INVESTMENT_FILE" ]; then
    cat "$INVESTMENT_FILE" >> "$OUTPUT_FILE"
    echo "  ✅ Investment: $INV_COUNT concepts"
else
    echo '{ "domain": { "name": "Investment", "path": "RBCZ:MIB:Investment" }, "concepts": [] }' >> "$OUTPUT_FILE"
    echo "  ⚠️  Investment: not found"
fi
echo ";" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Payments data
echo "// Payments domain" >> "$OUTPUT_FILE"
echo -n "const PAYMENTS_DATA = " >> "$OUTPUT_FILE"
if [ -f "$PAYMENTS_FILE" ]; then
    cat "$PAYMENTS_FILE" >> "$OUTPUT_FILE"
    echo "  ✅ Payments: $PAY_COUNT concepts"
else
    echo '{ "domain": { "name": "Payments", "path": "RBCZ:MIB:Payments" }, "concepts": [] }' >> "$OUTPUT_FILE"
    echo "  ⚠️  Payments: not found"
fi
echo ";" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Retail data
echo "// Retail domain" >> "$OUTPUT_FILE"
echo -n "const RETAIL_DATA = " >> "$OUTPUT_FILE"
if [ -f "$RETAIL_FILE" ]; then
    cat "$RETAIL_FILE" >> "$OUTPUT_FILE"
    echo "  ✅ Retail: $RET_COUNT concepts"
else
    echo '{ "domain": { "name": "Retail", "path": "RBCZ:Retail" }, "concepts": [] }' >> "$OUTPUT_FILE"
    echo "  ⚠️  Retail: not found"
fi
echo ";" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Export as BKB_ORG_DATA (merged with BKB_DATA by app.js)
echo "// Export for application (merged with BKB_DATA by app.js)" >> "$OUTPUT_FILE"
echo "window.BKB_ORG_DATA = {" >> "$OUTPUT_FILE"
echo "  domains: ORG_DOMAINS_DATA," >> "$OUTPUT_FILE"
echo "  investment: INVESTMENT_DATA," >> "$OUTPUT_FILE"
echo "  payments: PAYMENTS_DATA," >> "$OUTPUT_FILE"
echo "  retail: RETAIL_DATA" >> "$OUTPUT_FILE"
echo "};" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "console.log('🔐 Organization data loaded:', Object.keys(window.BKB_ORG_DATA));" >> "$OUTPUT_FILE"

# Report
FILE_SIZE=$(wc -c < "$OUTPUT_FILE" | tr -d ' ')
FILE_SIZE_KB=$((FILE_SIZE / 1024))
echo ""
echo "✅ Generated $OUTPUT_FILE"
echo "   Size: ${FILE_SIZE_KB} KB"
echo "   ⚠️  This file is gitignored - never commit!"
echo ""
echo "🚀 Ready! Open index.html in browser."
